<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'first_name' => 'Daphnée',
                'second_name' => 'Petronille',
                'surname' => 'Junkinson',
                'name_prefix' => 'Ms',
                'status' => 3,
                'email' => 'pjunkinson0@vk.com',
                'password' => 'oJ13yf9lj8',
                'tel' => '740-222-2341',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'first_name' => 'Marylène',
                'second_name' => 'Del',
                'surname' => 'Winslow',
                'name_prefix' => 'Honorable',
                'status' => 1,
                'email' => 'dwinslow1@fotki.com',
                'password' => 'fvyAFIo',
                'tel' => '971-981-0148',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'first_name' => 'Måns',
                'second_name' => 'Emma',
                'surname' => 'Spelling',
                'name_prefix' => 'Dr',
                'status' => 2,
                'email' => 'espelling2@hatena.ne.jp',
                'password' => 'CNxhew',
                'tel' => '360-990-5870',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'first_name' => 'Maëline',
                'second_name' => 'Ricca',
                'surname' => 'Brandin',
                'name_prefix' => 'Dr',
                'status' => 1,
                'email' => 'rbrandin3@psu.edu',
                'password' => 'C6dciuiyVs',
                'tel' => '776-421-2174',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'first_name' => 'Régine',
                'second_name' => 'Verile',
                'surname' => 'Manton',
                'name_prefix' => 'Mrs',
                'status' => 4,
                'email' => 'vmanton4@msu.edu',
                'password' => '3DVZsNiP',
                'tel' => '908-751-4900',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'first_name' => 'Laurène',
                'second_name' => 'Lizbeth',
                'surname' => 'Sebright',
                'name_prefix' => 'Honorable',
                'status' => 2,
                'email' => 'lsebright5@wordpress.com',
                'password' => 'QGVnIf65',
                'tel' => '613-493-1375',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'first_name' => 'Andréa',
                'second_name' => 'Alie',
                'surname' => 'Element',
                'name_prefix' => 'Mr',
                'status' => 4,
                'email' => 'aelement6@apache.org',
                'password' => 'oP356ueD',
                'tel' => '810-467-1086',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'first_name' => 'Erwéi',
                'second_name' => 'Vinita',
                'surname' => 'Domeney',
                'name_prefix' => 'Mr',
                'status' => 2,
                'email' => 'vdomeney7@blinklist.com',
                'password' => 'U04IPQLB',
                'tel' => '743-814-5137',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'first_name' => 'Laïla',
                'second_name' => 'Zarla',
                'surname' => 'Pascoe',
                'name_prefix' => 'Mr',
                'status' => 3,
                'email' => 'zpascoe8@gnu.org',
                'password' => 'ge7XktI7lE',
                'tel' => '413-987-6706',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'first_name' => 'Stévina',
                'second_name' => 'Hesther',
                'surname' => 'Turpie',
                'name_prefix' => 'Mr',
                'status' => 3,
                'email' => 'hturpie9@free.fr',
                'password' => 'WHc3LpyJu4H',
                'tel' => '424-869-1660',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'first_name' => 'Marlène',
                'second_name' => 'Ofelia',
                'surname' => 'Thackray',
                'name_prefix' => 'Dr',
                'status' => 3,
                'email' => 'othackraya@cbsnews.com',
                'password' => 'QqPY3sTlHS',
                'tel' => '505-110-5670',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'first_name' => 'Bérengère',
                'second_name' => 'Harriette',
                'surname' => 'Roycroft',
                'name_prefix' => 'Honorable',
                'status' => 1,
                'email' => 'hroycroftb@usa.gov',
                'password' => 'AgTmqGaA',
                'tel' => '134-508-1305',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'first_name' => 'Mélanie',
                'second_name' => 'Masha',
                'surname' => 'Leatherborrow',
                'name_prefix' => 'Mrs',
                'status' => 1,
                'email' => 'mleatherborrowc@yahoo.com',
                'password' => 'ZR22KTzDIGy',
                'tel' => '336-540-3204',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'first_name' => 'Séréna',
                'second_name' => 'Fionna',
                'surname' => 'Deyes',
                'name_prefix' => 'Mrs',
                'status' => 3,
                'email' => 'fdeyesd@fda.gov',
                'password' => 'kVwAQu41Emi',
                'tel' => '337-249-7098',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'first_name' => 'Cinéma',
                'second_name' => 'Pen',
                'surname' => 'Stebbins',
                'name_prefix' => 'Mr',
                'status' => 3,
                'email' => 'pstebbinse@usa.gov',
                'password' => 'kBryFtXjqcL0',
                'tel' => '330-216-8168',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'first_name' => 'Crééz',
                'second_name' => 'Millie',
                'surname' => 'Redmell',
                'name_prefix' => 'Ms',
                'status' => 2,
                'email' => 'mredmellf@unblog.fr',
                'password' => 'ZVX0tHyGBA',
                'tel' => '378-250-4566',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'first_name' => 'Aurélie',
                'second_name' => 'Leyla',
                'surname' => 'Bann',
                'name_prefix' => 'Rev',
                'status' => 4,
                'email' => 'lbanng@istockphoto.com',
                'password' => 'qWpfjQl',
                'tel' => '366-889-7562',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'first_name' => 'Crééz',
                'second_name' => 'Elnore',
                'surname' => 'Blacktin',
                'name_prefix' => 'Mrs',
                'status' => 4,
                'email' => 'eblacktinh@ustream.tv',
                'password' => 'qIKaKD',
                'tel' => '138-521-4964',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'first_name' => 'Esbjörn',
                'second_name' => 'Katharyn',
                'surname' => 'Tummond',
                'name_prefix' => 'Mr',
                'status' => 2,
                'email' => 'ktummondi@toplist.cz',
                'password' => 's4MdvO',
                'tel' => '743-296-2923',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'first_name' => 'Marie-françoise',
                'second_name' => 'Clo',
                'surname' => 'Tatershall',
                'name_prefix' => 'Mrs',
                'status' => 4,
                'email' => 'ctatershallj@smugmug.com',
                'password' => 'FygUWUoW',
                'tel' => '669-331-8033',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'first_name' => 'Léane',
                'second_name' => 'Marianna',
                'surname' => 'Haws',
                'name_prefix' => 'Rev',
                'status' => 2,
                'email' => 'mhawsk@taobao.com',
                'password' => 'oMJPIywlXAN',
                'tel' => '457-292-3502',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'first_name' => 'Lyséa',
                'second_name' => 'Danya',
                'surname' => 'State',
                'name_prefix' => 'Ms',
                'status' => 1,
                'email' => 'dstatel@merriam-webster.com',
                'password' => 'gK5HQSTr9dqG',
                'tel' => '519-689-9730',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'first_name' => 'Maïlys',
                'second_name' => 'Devan',
                'surname' => 'Lebreton',
                'name_prefix' => 'Ms',
                'status' => 2,
                'email' => 'dlebretonm@comsenz.com',
                'password' => 'dZ9LzE',
                'tel' => '577-995-5371',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'first_name' => 'Zhì',
                'second_name' => 'Lethia',
                'surname' => 'Gatty',
                'name_prefix' => 'Honorable',
                'status' => 4,
                'email' => 'lgattyn@bloomberg.com',
                'password' => 'qeDfIh8',
                'tel' => '296-499-9362',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'first_name' => 'Kuí',
                'second_name' => 'Corry',
                'surname' => 'Carlill',
                'name_prefix' => 'Mr',
                'status' => 4,
                'email' => 'ccarlillo@360.cn',
                'password' => 'q7YxBgPm',
                'tel' => '877-547-6637',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'first_name' => 'Nuó',
                'second_name' => 'Maddie',
                'surname' => 'Schwier',
                'name_prefix' => 'Rev',
                'status' => 1,
                'email' => 'mschwierp@storify.com',
                'password' => 'yp9xFu',
                'tel' => '231-322-2438',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'first_name' => 'Lucrèce',
                'second_name' => 'Bridie',
                'surname' => 'Tidy',
                'name_prefix' => 'Honorable',
                'status' => 3,
                'email' => 'btidyq@thetimes.co.uk',
                'password' => 'VPwrH6kMfVes',
                'tel' => '992-590-9158',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'first_name' => 'Maëlyss',
                'second_name' => 'Shoshanna',
                'surname' => 'Bertome',
                'name_prefix' => 'Dr',
                'status' => 3,
                'email' => 'sbertomer@google.it',
                'password' => 'SpB2ANv69Dcr',
                'tel' => '196-415-2313',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'first_name' => 'Gwenaëlle',
                'second_name' => 'Ali',
                'surname' => 'Rutherfoord',
                'name_prefix' => 'Mrs',
                'status' => 3,
                'email' => 'arutherfoords@google.co.jp',
                'password' => 'KRAUNqlWBmd',
                'tel' => '659-420-2100',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'first_name' => 'Faîtes',
                'second_name' => 'Cathrin',
                'surname' => 'Zini',
                'name_prefix' => 'Dr',
                'status' => 2,
                'email' => 'czinit@mysql.com',
                'password' => '3HbFemxU',
                'tel' => '616-997-4315',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'first_name' => 'Bénédicte',
                'second_name' => 'Wallie',
                'surname' => 'Tows',
                'name_prefix' => 'Ms',
                'status' => 4,
                'email' => 'wtowsu@uiuc.edu',
                'password' => 'wyZK9Eax',
                'tel' => '700-487-5479',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'first_name' => 'Crééz',
                'second_name' => 'Ashien',
                'surname' => 'Mayell',
                'name_prefix' => 'Dr',
                'status' => 3,
                'email' => 'amayellv@reference.com',
                'password' => '3c6ZWilAoAM',
                'tel' => '264-441-9091',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'first_name' => 'Lucrèce',
                'second_name' => 'Frankie',
                'surname' => 'Brayne',
                'name_prefix' => 'Mr',
                'status' => 2,
                'email' => 'fbraynew@icio.us',
                'password' => 'Kiv77Nh',
                'tel' => '253-413-1876',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'first_name' => 'Noémie',
                'second_name' => 'Phyllis',
                'surname' => 'Wyeth',
                'name_prefix' => 'Honorable',
                'status' => 3,
                'email' => 'pwyethx@dot.gov',
                'password' => 'raclo0Q',
                'tel' => '991-461-6588',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'first_name' => 'Gaëlle',
                'second_name' => 'Alica',
                'surname' => 'Pack',
                'name_prefix' => 'Rev',
                'status' => 4,
                'email' => 'apacky@dyndns.org',
                'password' => 'lPBayv9tBg',
                'tel' => '750-885-4606',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'first_name' => 'Gaëlle',
                'second_name' => 'Ted',
                'surname' => 'Lowy',
                'name_prefix' => 'Mr',
                'status' => 1,
                'email' => 'tlowyz@usnews.com',
                'password' => '9OIZm3s',
                'tel' => '851-297-1633',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'first_name' => 'Intéressant',
                'second_name' => 'Isabelita',
                'surname' => 'Withams',
                'name_prefix' => 'Mrs',
                'status' => 3,
                'email' => 'iwithams10@fema.gov',
                'password' => 'IglxZsmW89',
                'tel' => '254-587-1284',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'first_name' => 'Adélaïde',
                'second_name' => 'Calli',
                'surname' => 'de Villier',
                'name_prefix' => 'Mrs',
                'status' => 3,
                'email' => 'cdevillier11@woothemes.com',
                'password' => '7cDh1Vti1c',
                'tel' => '315-736-8407',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'first_name' => 'Marie-noël',
                'second_name' => 'Aubrie',
                'surname' => 'Clemens',
                'name_prefix' => 'Dr',
                'status' => 1,
                'email' => 'aclemens12@arstechnica.com',
                'password' => 'iqONVWX',
                'tel' => '777-202-0699',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'first_name' => 'Maïlys',
                'second_name' => 'Noreen',
                'surname' => 'St Ledger',
                'name_prefix' => 'Mrs',
                'status' => 1,
                'email' => 'nstledger13@cocolog-nifty.com',
                'password' => 'VN6uDI',
                'tel' => '399-574-3649',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'first_name' => 'Mélys',
                'second_name' => 'Marys',
                'surname' => 'Cunnell',
                'name_prefix' => 'Mr',
                'status' => 3,
                'email' => 'mcunnell14@ehow.com',
                'password' => '3DsYxjeA',
                'tel' => '311-634-6933',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'first_name' => 'Gösta',
                'second_name' => 'Ginny',
                'surname' => 'Seif',
                'name_prefix' => 'Mr',
                'status' => 4,
                'email' => 'gseif15@nsw.gov.au',
                'password' => '2wQlYBO',
                'tel' => '475-208-0180',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'first_name' => 'Marie-hélène',
                'second_name' => 'Marilin',
                'surname' => 'Keefe',
                'name_prefix' => 'Honorable',
                'status' => 3,
                'email' => 'mkeefe16@dyndns.org',
                'password' => 'z4TrAeuO2',
                'tel' => '810-633-0023',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'first_name' => 'Vérane',
                'second_name' => 'Shandeigh',
                'surname' => 'Parnby',
                'name_prefix' => 'Dr',
                'status' => 1,
                'email' => 'sparnby17@twitter.com',
                'password' => '6nqL0f3xAB',
                'tel' => '593-875-7703',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'first_name' => 'Félicie',
                'second_name' => 'Janean',
                'surname' => 'Maps',
                'name_prefix' => 'Dr',
                'status' => 4,
                'email' => 'jmaps18@cafepress.com',
                'password' => 'UqVztFbypa',
                'tel' => '748-297-5835',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'first_name' => 'Yóu',
                'second_name' => 'Luz',
                'surname' => 'Standish-Brooks',
                'name_prefix' => 'Ms',
                'status' => 3,
                'email' => 'lstandishbrooks19@lulu.com',
                'password' => 'BT8MVOw',
                'tel' => '524-840-9983',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'first_name' => 'Vénus',
                'second_name' => 'Shari',
                'surname' => 'Exon',
                'name_prefix' => 'Rev',
                'status' => 4,
                'email' => 'sexon1a@xrea.com',
                'password' => '94FdApgrO',
                'tel' => '844-748-9440',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'first_name' => 'Lorène',
                'second_name' => 'Babbette',
                'surname' => 'Dugget',
                'name_prefix' => 'Mrs',
                'status' => 3,
                'email' => 'bdugget1b@buzzfeed.com',
                'password' => 'aPaqnOH',
                'tel' => '355-909-8376',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'first_name' => 'Lorène',
                'second_name' => 'Sarine',
                'surname' => 'Georgi',
                'name_prefix' => 'Honorable',
                'status' => 4,
                'email' => 'sgeorgi1c@typepad.com',
                'password' => 'JBPmf1XFg',
                'tel' => '148-603-1867',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'first_name' => 'Lorène',
                'second_name' => 'Christan',
                'surname' => 'Andreacci',
                'name_prefix' => 'Mrs',
                'status' => 1,
                'email' => 'candreacci1d@google.com.au',
                'password' => '8phJuopsCL1',
                'tel' => '584-728-8060',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'first_name' => 'Uò',
                'second_name' => 'Noreen',
                'surname' => 'Baxandall',
                'name_prefix' => 'Rev',
                'status' => 4,
                'email' => 'nbaxandall1e@networksolutions.com',
                'password' => 'asvz4LItGR3l',
                'tel' => '519-868-7439',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'first_name' => 'Françoise',
                'second_name' => 'Anallese',
                'surname' => 'Feldharker',
                'name_prefix' => 'Mrs',
                'status' => 3,
                'email' => 'afeldharker1f@chron.com',
                'password' => 'V4Lr5kye',
                'tel' => '829-853-8897',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'first_name' => 'Lèi',
                'second_name' => 'Jacynth',
                'surname' => 'Sertin',
                'name_prefix' => 'Rev',
                'status' => 4,
                'email' => 'jsertin1g@time.com',
                'password' => 'lEVU8StFw',
                'tel' => '482-934-1209',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'first_name' => 'Fèi',
                'second_name' => 'Fiona',
                'surname' => 'Colkett',
                'name_prefix' => 'Ms',
                'status' => 4,
                'email' => 'fcolkett1h@quantcast.com',
                'password' => 'GckloJjcgdj',
                'tel' => '275-250-7545',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'first_name' => 'Mén',
                'second_name' => 'Fayth',
                'surname' => 'Boydon',
                'name_prefix' => 'Ms',
                'status' => 2,
                'email' => 'fboydon1i@google.cn',
                'password' => 'GYOXMewS',
                'tel' => '657-776-0302',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'first_name' => 'Gaëlle',
                'second_name' => 'Gale',
                'surname' => 'Velde',
                'name_prefix' => 'Honorable',
                'status' => 4,
                'email' => 'gvelde1j@weebly.com',
                'password' => 'XnrWojQiTp',
                'tel' => '688-216-5868',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'first_name' => 'Illustrée',
                'second_name' => 'Stella',
                'surname' => 'Batterbee',
                'name_prefix' => 'Dr',
                'status' => 4,
                'email' => 'sbatterbee1k@skyrock.com',
                'password' => 'Y4JyoWRVFxNg',
                'tel' => '680-877-6913',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'first_name' => 'Anaïs',
                'second_name' => 'Elvina',
                'surname' => 'O\'Nolan',
                'name_prefix' => 'Honorable',
                'status' => 2,
                'email' => 'eonolan1l@marketwatch.com',
                'password' => 'Slg04Jn',
                'tel' => '863-513-7463',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'first_name' => 'Noëlla',
                'second_name' => 'Nalani',
                'surname' => 'Lindenbluth',
                'name_prefix' => 'Honorable',
                'status' => 1,
                'email' => 'nlindenbluth1m@scientificamerican.com',
                'password' => 'qOJPLXaiPsM',
                'tel' => '582-977-0360',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'first_name' => 'Annotés',
                'second_name' => 'Josefa',
                'surname' => 'Fitchen',
                'name_prefix' => 'Mrs',
                'status' => 2,
                'email' => 'jfitchen1n@sun.com',
                'password' => '3tucHGFZBb0',
                'tel' => '859-791-9397',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'first_name' => 'Danièle',
                'second_name' => 'Latia',
                'surname' => 'Sotheby',
                'name_prefix' => 'Honorable',
                'status' => 2,
                'email' => 'lsotheby1o@craigslist.org',
                'password' => 'DjvKMk',
                'tel' => '923-445-4827',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'first_name' => 'Eléa',
                'second_name' => 'Seline',
                'surname' => 'Bellson',
                'name_prefix' => 'Honorable',
                'status' => 3,
                'email' => 'sbellson1p@squarespace.com',
                'password' => 'DI5TLDeam9',
                'tel' => '925-313-9165',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'first_name' => 'Lauréna',
                'second_name' => 'Liza',
                'surname' => 'Gawn',
                'name_prefix' => 'Rev',
                'status' => 4,
                'email' => 'lgawn1q@qq.com',
                'password' => '1FvUh0s1',
                'tel' => '867-459-7986',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'first_name' => 'Uò',
                'second_name' => 'Loraine',
                'surname' => 'Robey',
                'name_prefix' => 'Mrs',
                'status' => 2,
                'email' => 'lrobey1r@chronoengine.com',
                'password' => 'C8r2piHjCO8j',
                'tel' => '134-341-3404',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'first_name' => 'Mélodie',
                'second_name' => 'Valida',
                'surname' => 'Presslie',
                'name_prefix' => 'Ms',
                'status' => 3,
                'email' => 'vpresslie1s@mashable.com',
                'password' => 'NNxOB2',
                'tel' => '530-768-3265',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'first_name' => 'Adélie',
                'second_name' => 'Kipp',
                'surname' => 'Furse',
                'name_prefix' => 'Honorable',
                'status' => 1,
                'email' => 'kfurse1t@ft.com',
                'password' => 'orEbg7kWBox',
                'tel' => '127-770-2396',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'first_name' => 'Daphnée',
                'second_name' => 'Dorian',
                'surname' => 'Raggatt',
                'name_prefix' => 'Honorable',
                'status' => 1,
                'email' => 'draggatt1u@themeforest.net',
                'password' => '6GASQM3ViCWE',
                'tel' => '654-953-7267',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'first_name' => 'Lài',
                'second_name' => 'Linda',
                'surname' => 'Nacey',
                'name_prefix' => 'Ms',
                'status' => 2,
                'email' => 'lnacey1v@cargocollective.com',
                'password' => 'Xhr1fYKKcel8',
                'tel' => '986-827-6519',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'first_name' => 'Lyséa',
                'second_name' => 'Dorothee',
                'surname' => 'Ties',
                'name_prefix' => 'Honorable',
                'status' => 2,
                'email' => 'dties1w@domainmarket.com',
                'password' => '6bTyGgATa1',
                'tel' => '770-541-5949',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'first_name' => 'Mélys',
                'second_name' => 'Gelya',
                'surname' => 'Morgen',
                'name_prefix' => 'Mr',
                'status' => 4,
                'email' => 'gmorgen1x@shinystat.com',
                'password' => 'DP8ZFShsSCW',
                'tel' => '924-757-4566',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'first_name' => 'Solène',
                'second_name' => 'Kriste',
                'surname' => 'Dinsey',
                'name_prefix' => 'Mrs',
                'status' => 3,
                'email' => 'kdinsey1y@myspace.com',
                'password' => 'egQ1CoDi8i',
                'tel' => '332-638-9217',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'first_name' => 'Mélys',
                'second_name' => 'Morgana',
                'surname' => 'Hartshorn',
                'name_prefix' => 'Mrs',
                'status' => 1,
                'email' => 'mhartshorn1z@privacy.gov.au',
                'password' => 'EgGpYbbWq',
                'tel' => '783-418-3001',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'first_name' => 'Léonie',
                'second_name' => 'Drucill',
                'surname' => 'Hewertson',
                'name_prefix' => 'Mr',
                'status' => 2,
                'email' => 'dhewertson20@house.gov',
                'password' => 'Jp8vFtq',
                'tel' => '192-841-6404',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'first_name' => 'Erwéi',
                'second_name' => 'Cherin',
                'surname' => 'Padula',
                'name_prefix' => 'Ms',
                'status' => 4,
                'email' => 'cpadula21@usgs.gov',
                'password' => 'yHbjLfH6Mgb',
                'tel' => '319-964-9447',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'first_name' => 'Gaïa',
                'second_name' => 'Loree',
                'surname' => 'Hartill',
                'name_prefix' => 'Mr',
                'status' => 3,
                'email' => 'lhartill22@shinystat.com',
                'password' => 'ayRGWaOjNHq',
                'tel' => '691-345-7742',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'first_name' => 'Loïc',
                'second_name' => 'Lise',
                'surname' => 'Wohlers',
                'name_prefix' => 'Mr',
                'status' => 4,
                'email' => 'lwohlers23@sohu.com',
                'password' => 'B7KH9r8',
                'tel' => '811-880-2351',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'first_name' => 'Stéphanie',
                'second_name' => 'Corette',
                'surname' => 'Birdwistle',
                'name_prefix' => 'Rev',
                'status' => 3,
                'email' => 'cbirdwistle24@seesaa.net',
                'password' => 'arTiwURYU',
                'tel' => '833-126-4341',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'first_name' => 'Naëlle',
                'second_name' => 'Sonnnie',
                'surname' => 'Waterhowse',
                'name_prefix' => 'Dr',
                'status' => 1,
                'email' => 'swaterhowse25@google.ru',
                'password' => '5OPdDiHhAI',
                'tel' => '951-313-4251',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'first_name' => 'Solène',
                'second_name' => 'Lura',
                'surname' => 'Knowlys',
                'name_prefix' => 'Mr',
                'status' => 2,
                'email' => 'lknowlys26@moonfruit.com',
                'password' => 'iyfFBdp',
                'tel' => '653-859-1054',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'first_name' => 'Célestine',
                'second_name' => 'Rafa',
                'surname' => 'Staddon',
                'name_prefix' => 'Mr',
                'status' => 4,
                'email' => 'rstaddon27@timesonline.co.uk',
                'password' => 'yvUCwQ',
                'tel' => '291-251-4100',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'first_name' => 'Hélène',
                'second_name' => 'Gertruda',
                'surname' => 'Dullaghan',
                'name_prefix' => 'Mrs',
                'status' => 1,
                'email' => 'gdullaghan28@opera.com',
                'password' => 'AMN8QYw',
                'tel' => '638-714-1568',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'first_name' => 'Örjan',
                'second_name' => 'Elset',
                'surname' => 'Korn',
                'name_prefix' => 'Mrs',
                'status' => 2,
                'email' => 'ekorn29@yellowbook.com',
                'password' => 'VUzVo63gIEW3',
                'tel' => '538-395-2236',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'first_name' => 'Geneviève',
                'second_name' => 'Emalia',
                'surname' => 'Raulstone',
                'name_prefix' => 'Mr',
                'status' => 4,
                'email' => 'eraulstone2a@list-manage.com',
                'password' => 'w8dPD7QEK',
                'tel' => '835-607-4690',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'first_name' => 'Yénora',
                'second_name' => 'Barry',
                'surname' => 'Stears',
                'name_prefix' => 'Honorable',
                'status' => 3,
                'email' => 'bstears2b@istockphoto.com',
                'password' => 'JNAaKUz',
                'tel' => '812-390-9878',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'first_name' => 'Björn',
                'second_name' => 'Letizia',
                'surname' => 'Waddicor',
                'name_prefix' => 'Mr',
                'status' => 4,
                'email' => 'lwaddicor2c@illinois.edu',
                'password' => '66MVzRn',
                'tel' => '293-485-3201',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'first_name' => 'Kallisté',
                'second_name' => 'Maxi',
                'surname' => 'Cadding',
                'name_prefix' => 'Dr',
                'status' => 4,
                'email' => 'mcadding2d@trellian.com',
                'password' => 'Kan49dGPNRQ',
                'tel' => '484-420-2542',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'first_name' => 'Véronique',
                'second_name' => 'Peri',
                'surname' => 'Bauduccio',
                'name_prefix' => 'Ms',
                'status' => 1,
                'email' => 'pbauduccio2e@dion.ne.jp',
                'password' => 'UnWnfm',
                'tel' => '312-857-2997',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'first_name' => 'Naéva',
                'second_name' => 'Dallas',
                'surname' => 'Frenzl',
                'name_prefix' => 'Mrs',
                'status' => 1,
                'email' => 'dfrenzl2f@canalblog.com',
                'password' => 'Ee28kyR9v0M5',
                'tel' => '420-437-5991',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'first_name' => 'Mélinda',
                'second_name' => 'Pet',
                'surname' => 'Margaritelli',
                'name_prefix' => 'Dr',
                'status' => 3,
                'email' => 'pmargaritelli2g@webnode.com',
                'password' => 'GffHhE',
                'tel' => '366-956-0811',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'first_name' => 'Mélina',
                'second_name' => 'Eilis',
                'surname' => 'Schulke',
                'name_prefix' => 'Dr',
                'status' => 4,
                'email' => 'eschulke2h@about.com',
                'password' => 'sfb3NWovg',
                'tel' => '675-649-6079',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'first_name' => 'Gaétane',
                'second_name' => 'Abbe',
                'surname' => 'McManamen',
                'name_prefix' => 'Mrs',
                'status' => 3,
                'email' => 'amcmanamen2i@phoca.cz',
                'password' => 'DHvqwI1Y',
                'tel' => '425-296-2594',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'first_name' => 'Liè',
                'second_name' => 'Lucinda',
                'surname' => 'Drayson',
                'name_prefix' => 'Mr',
                'status' => 2,
                'email' => 'ldrayson2j@youku.com',
                'password' => 'ON6CtknU',
                'tel' => '267-786-0969',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'first_name' => 'Eléa',
                'second_name' => 'Lorraine',
                'surname' => 'Longhorne',
                'name_prefix' => 'Dr',
                'status' => 1,
                'email' => 'llonghorne2k@fc2.com',
                'password' => '5Fbhuj',
                'tel' => '542-513-7208',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'first_name' => 'Séverine',
                'second_name' => 'Penelope',
                'surname' => 'Tinman',
                'name_prefix' => 'Dr',
                'status' => 2,
                'email' => 'ptinman2l@xing.com',
                'password' => 'DID2wbIMLzd8',
                'tel' => '436-129-1381',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'first_name' => 'Yóu',
                'second_name' => 'Ashla',
                'surname' => 'Bunce',
                'name_prefix' => 'Dr',
                'status' => 3,
                'email' => 'abunce2m@state.gov',
                'password' => 'eqztvAo4p',
                'tel' => '907-594-8140',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'first_name' => 'Publicité',
                'second_name' => 'Mellie',
                'surname' => 'Kelwick',
                'name_prefix' => 'Ms',
                'status' => 3,
                'email' => 'mkelwick2n@jimdo.com',
                'password' => 'Fy660Db',
                'tel' => '194-886-3318',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'first_name' => 'Annotés',
                'second_name' => 'Leshia',
                'surname' => 'Slowly',
                'name_prefix' => 'Rev',
                'status' => 4,
                'email' => 'lslowly2o@yale.edu',
                'password' => 'kx0DlMBn0UlV',
                'tel' => '779-838-9843',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'first_name' => 'Séréna',
                'second_name' => 'Minerva',
                'surname' => 'Emeny',
                'name_prefix' => 'Ms',
                'status' => 3,
                'email' => 'memeny2p@ebay.co.uk',
                'password' => 'nEpFTtt7E',
                'tel' => '776-567-1753',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'first_name' => 'Réservés',
                'second_name' => 'Mareah',
                'surname' => 'Thorsby',
                'name_prefix' => 'Ms',
                'status' => 1,
                'email' => 'mthorsby2q@nih.gov',
                'password' => 'ug55XCrj',
                'tel' => '212-842-9275',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'first_name' => 'Some',
                'second_name' => 'Other',
                'surname' => 'Guy',
                'name_prefix' => 'Student',
                'status' => 1,
                'email' => 'someotherguy@gmail.com',
                'password' => '123456',
                'tel' => '723456789',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'first_name' => 'Brian',
                'second_name' => 'Mutinda',
                'surname' => 'Kasarani',
                'name_prefix' => 'Student',
                'status' => 4,
                'email' => 'BrianMutinda@epa.gov',
                'password' => 'SMqS4C',
                'tel' => '712345678',
                'remember_token' => NULL,
                'created_at' => '2018-06-23 09:44:35',
                'updated_at' => '2018-06-23 09:44:39',
            ),
            101 => 
            array (
                'first_name' => 'Erick',
                'second_name' => 'Njiru',
                'surname' => 'Kirabui',
                'name_prefix' => 'Dr',
                'status' => 1,
                'email' => 'ericknjiru454@gmail.com',
                'password' => '$2y$10$ZcrHbE9cNv8Owlu8m5jWNOpok9ENUmua9gNtEiPrn1zecPW00aTBW',
                'tel' => '718931359',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'first_name' => 'Derick',
                'second_name' => 'Kiraui',
                'surname' => 'Kirui',
                'name_prefix' => 'Student',
                'status' => 1,
                'email' => 'eriknjiru63@gmail.com',
                'password' => '$2y$10$ZcrHbE9cNv8Owlu8m5jWNOpok9ENUmua9gNtEiPrn1zecPW00aTBW',
                'tel' => '718931959',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}